### ISSUE TITLE
Missing `tal.cabal`

### ISSUE THREAD

**Issue by jmitchell** [sweirich/tal#1]
Currently it takes work to identify this project's dependencies and load it using stack or cabal.

I [made a `tal.cabal`](https://github.com/jmitchell/tal/commit/37563ec239b121340cd090a512ee145982a6e3b8) and confirmed a new stack project can load it (see commit comment). If you're interested I can submit a pull request with at least these changes:
- set the maintainer field to the email address in your GH profile
- set the homepage field to this repository

Thanks for releasing this code. I'm eager to study it more.

**Comment by sweirich** [comment]
Thanks!  Please do submit the pull request.   And let me know if you have questions about the code.
